-- 1) What is the total revenue generated by male vs female customers?
SELECT 
	gender,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;


-- 2) Which customer used a discount but still spent mpre than avg purchase amount?
SELECT
	customer_id,
    purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount > (SELECT AVG(purchase_amount) FROM Customer);


-- 3) Which are the top 5 products with the highest avg review rating?
SELECT
	item_purchased,
	AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC LIMIT 5;


-- 4) Compare the avg Purchase Amounts between Standard and Express Shipping
SELECT
	shipping_type,
    AVG(purchase_amount)
FROM customer
WHERE shipping_type IN('Express', 'Standard')
GROUP BY shipping_type;


-- 5) Do subscribed customers spend more? Compare avg spend 
-- and total revenue between subscribers and non-subscribers
SELECT
	COUNT(customer_id) AS total_customers,
	AVG(purchase_amount) AS avg_purchase,
    SUM(purchase_amount) AS total_revenue,
    subscription_status
FROM customer
GROUP BY subscription_status;


-- 6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    COUNT(*) AS total_purchases,
    SUM(discount_applied = 'Yes') AS discounted_purchases,
    ROUND(SUM(discount_applied = 'Yes') / COUNT(*) * 100, 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;


-- 7) Segment customers into New, Returning, and Loyal based on their
-- total number of prev. purchases, and show count of each segment
SELECT
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer
GROUP BY customer_segment;
  
  
-- 8) What are the top 3 purchased products within each category
SELECT item_purchased, category, purchase_count
FROM (
    SELECT 
        item_purchased,
        category,
        COUNT(*) AS purchase_count,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY item_purchased, category
) ranked
WHERE rnk <= 3
ORDER BY category, purchase_count DESC;


-- 9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT 
    CASE 
        WHEN previous_purchases > 5 THEN 'Repeat Buyer'
        ELSE 'Non-Repeat Buyer'
    END AS buyer_type,
    subscription_status,
    COUNT(*) AS customer_count,
    ROUND(COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY 
        CASE WHEN previous_purchases > 5 THEN 'Repeat Buyer' ELSE 'Non-Repeat Buyer' END
    ), 2) AS percentage
FROM customer
GROUP BY buyer_type, subscription_status
ORDER BY buyer_type, subscription_status;

-- 10) What is the revenue contribution of each age group?
SELECT
	age_group,
    SUM(purchase_amount) AS revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;